"""empty message

Revision ID: 3176be20566f
Revises: 49fad688b87e
Create Date: 2024-03-31 21:22:01.477319

"""
from alembic import op
import sqlalchemy as sa
import model

# revision identifiers, used by Alembic.
revision = '3176be20566f'
down_revision = '49fad688b87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_image', schema=None) as batch_op:
        batch_op.alter_column('last_mod',
               existing_type=sa.DATETIME(),
               type_=model.ISODateTime(length=19),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('output_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_mod', model.ISODateTime(length=19), nullable=True))

    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_mod', model.ISODateTime(length=19), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('last_mod',
               existing_type=sa.DATETIME(),
               type_=model.ISODateTime(length=19),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('last_mod',
               existing_type=model.ISODateTime(length=19),
               type_=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.drop_column('last_mod')

    with op.batch_alter_table('output_image', schema=None) as batch_op:
        batch_op.drop_column('last_mod')

    with op.batch_alter_table('original_image', schema=None) as batch_op:
        batch_op.alter_column('last_mod',
               existing_type=model.ISODateTime(length=19),
               type_=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
