"""empty message

Revision ID: 5226129d64c2
Revises: 92f5c32b9509
Create Date: 2024-04-02 11:14:33.226259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5226129d64c2'
down_revision = '92f5c32b9509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'original_image', ['img_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('img_id')

    # ### end Alembic commands ###
