"""empty message

Revision ID: 5c166d36c3b7
Revises: f29151b763c4
Create Date: 2024-04-06 10:30:50.838127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c166d36c3b7'
down_revision = 'f29151b763c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['thumbnail_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
