"""empty message

Revision ID: 747db3e326d1
Revises: 5c166d36c3b7
Create Date: 2024-04-06 10:31:29.321030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747db3e326d1'
down_revision = '5c166d36c3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
