"""empty message

Revision ID: a5d24a8a1b10
Revises: 8f84a2bbdb1b
Create Date: 2024-04-01 14:43:23.019537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d24a8a1b10'
down_revision = '8f84a2bbdb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_image', schema=None) as batch_op:
        batch_op.alter_column('style',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_image', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('style',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
