"""empty message

Revision ID: f29151b763c4
Revises: 39eeab4c8549
Create Date: 2024-04-02 19:04:18.568324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29151b763c4'
down_revision = '39eeab4c8549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_type', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
